### ISSUE TITLE
Various issues with MultiLayerNetwork.java

### ISSUE THREAD

**Issue by delip** [SkymindIO/deeplearning4j#118]
1) https://github.com/SkymindIO/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L91
Should this null check happen early?
Also, for null checks Preconditions.checkNotNull() is nice to distinguish between precondition checking vs. some other null-based branching.

2) https://github.com/SkymindIO/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L112
Dereferencing layerWiseConfigurations here can cause an NPE when layerWiseConfigurations == null (see condition in the line before)

3) https://github.com/SkymindIO/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L190

The last two conditions may be removed.

4) https://github.com/SkymindIO/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L733

Lines 733-734 should be moved inside the try block.

5) https://github.com/SkymindIO/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L580
The weights and biases updated in lines 580 and 581 are not used anywhere else in their scope. What's the point? Am I missing something?

6) https://github.com/SkymindIO/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L852
Lines 852, 853, 854 may be deleted.

**Comment by agibsonccc** [comment]
Majorly helpful. Lots of relics from the refactoring.
