### ISSUE TITLE
How can I build a convolutional neural network with DL4J?

### ISSUE THREAD

**Issue by CogCom** [SkymindIO/deeplearning4j#119]
I can't find any Class or API of DL4J can help me build a convolutional neural network.

**Comment by agibsonccc** [comment]
Little late for me atm...will post an example tomorrow. The crux of it is in 0.0.3.3: everything is a layer. Right now, we have a max pooling layer:
https://github.com/SkymindIO/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/ConvolutionDownSampleLayer.java

**Comment by CogCom** [comment]
thank you so much.
