### ISSUE TITLE
Convolutional neural network problem..

### ISSUE THREAD

**Issue by CogCom** [SkymindIO/deeplearning4j#120]
Can you post a completed example of building a CNN with DL4J ?

I know there is a ConvolutionDownSampleLayer in DL4J, however, how to combine it and MultiLayerNeuralNetwork, and how to train them together  with BP ?

**Comment by agibsonccc** [comment]
Here's a complete conv net to get you started. The architecture is LeNet:
https://github.com/SkymindIO/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/models/layers/ConvolutionDownSampleLayerTest.java#L67


2 things of note I need to document: post processing the feature matrix so the 4d tensor gets down sampled to do 2d for a feature matrix.

**Comment by CogCom** [comment]
It‘s great. Thank you for your contribution.
