### ISSUE TITLE
Word2Vec Loader

### ISSUE THREAD

**Issue by sinjax** [SkymindIO/deeplearning4j#121]
The class org.deeplearning4j.models.word2vec.loader.Word2VecLoader seems to no longer exist. It seemed to disappear from the repository around the 30th of december. 

That aside, the latest google news dump seems to not load correctly using the old Word2VecLoader code. There was a bug fix inroduced at some point which skips null word entries, however the way it does so is incorrect. 

Is loading of word2vec models released by google and other folks still supported?

**Comment by agibsonccc** [comment]
This has been renamed to WordVectorSerializer in light of adding other models such as glove and paragraphvectors. I will be updating the docs for this when the 3.3 release goes out on maven central.

**Comment by sinjax** [comment]
Cool beans, two things.
1) The solution to dealing with empty words is incorrect. If those words are empty and yet have features then this implementation will not correctly read beyond the empty word.
2) The dis.read() at the end of the while loop results in the first letter of the following word to be stripped, this is in fact the reason why there are so many "empty words". 

Also the new imeplemetation writes temporary files then reads them back. My version loads all the vectors into a fat float[][] and instead of the loop starting line 108, I just use Nd4j.create()... seems to work fine so long as you are careful with how you write to said fat float[][]

**Comment by agibsonccc** [comment]
Care to submit a pull request?
