### ISSUE TITLE
WordVectorSerializer loadGoogleModel

### ISSUE THREAD

**Issue by dgaddy** [SkymindIO/deeplearning4j#134]
There are a couple of issues with loading the Word2Vec model.
When loading the pretrained model from the project homepage (GoogleNews-vectors-negative300.bin.gz), the first letter of each word is cut off because the loader expects newlines at the end of every vector, but this model does not have these newlines.  This was mentioned in the comments of issue #121 before, but has not been fixed.  Removing dis.read(); at the end of the while loop and adding a "if (b == 10) b = dis.readByte();" after "byte b = dis.readByte();" in readString (in case the newline does appear) seems to fix the problem.
There also seem to be problems caused by the "UNK" unknown word that is added to the cache in its constructor.  It causes the vectors to be misaligned when loading because the code assumes vectorPaths to be the same size as cache.numWords(), but numWords is one larger.

**Comment by agibsonccc** [comment]
https://github.com/SkymindIO/deeplearning4j/blob/5d1f52a82fd4d4e3f476dbe93a34e3f9e22b7818/deeplearning4j-scaleout/deeplearning4j-nlp/src/test/java/org/deeplearning4j/models/word2vec/WordVectorSerializerTest.java#L47

Downloads current ---> runs it ---> works. Made more efficient in the process.
