### ISSUE TITLE
o.d.b.v.BaseTextVectorizer - latch count -109 with queued 5975 loop

### ISSUE THREAD

**Issue by ckd002** [SkymindIO/deeplearning4j#135]
In attempting to create my own BagOfWords example i encountered this issue. I'm not sure if It's an issue with my code or something greater, but I was told to file a bug report so here it is. 

I am using Mac OSX
DL4J Version 0.0.3.2.7
ND4J Version0.0.3.5.1

My code is as follows:

```
import org.deeplearning4j.bagofwords.vectorizer.BagOfWordsVectorizer;
import org.deeplearning4j.models.word2vec.wordstore.VocabCache;
import org.deeplearning4j.models.word2vec.wordstore.inmemory.InMemoryLookupCache;
import org.deeplearning4j.text.documentiterator.DocumentIterator;
import org.deeplearning4j.text.documentiterator.FileDocumentIterator;
import org.deeplearning4j.text.tokenization.tokenizerfactory.DefaultTokenizerFactory;
import org.deeplearning4j.text.tokenization.tokenizerfactory.TokenizerFactory;
import org.nd4j.linalg.dataset.DataSet;

public class BagOfWords {
	private static TokenizerFactory tokenizer = new DefaultTokenizerFactory();
	private static BagOfWordsVectorizer vectorizer;
	private static VocabCache cache;
	private static DataSet data;
	
		
	public static void main(String[] args) {		
		DocumentIterator iter = new FileDocumentIterator("./src/main/resources/testing/");
		cache = new InMemoryLookupCache.Builder().lr(2e-5).vectorLength(100).build();

		vectorizer = (BagOfWordsVectorizer) new BagOfWordsVectorizer.Builder().iterate(iter).tokenize(tokenizer).build();
		vectorizer.fit();
		
		System.out.println("HERE");
		data = vectorizer.vectorize();
		System.out.println(data);
	}

}
```

And this is what gets printed to the console:
![screen shot 2015-01-28 at 5 14 46 pm](https://cloud.githubusercontent.com/assets/1816148/5948276/9bf208de-a711-11e4-9125-b1c273841a65.png)

**Comment by dav009** [comment]
I've got the same issue, any feedback?

**Comment by dav009** [comment]
@ckd002 Hey, I was seeing the same output when I was running the code within IntelliJ (endless loops of "latch count...X Y"..)
.
Once I generate the jar and run it, everything goes smoothly.

**Comment by agibsonccc** [comment]
What have you did with 0.0.3.3.x?

**Comment by dav009** [comment]
- nd4j: 0.0.3.5.3
- dl4j: 0.0.3.2.7
 - when running on intelliJ (I get loops of batches). Generating the jar and running via the terminal seems to get around it. Probably has to do with intelliJ's configuration.


I will play with 0.0.3.3.x and check if the same happens.

**Comment by dav009** [comment]
It works fine in intelliJ on` 0.0.3.3.3.alpha1-SNAPSHOT` :+1:
