### ISSUE TITLE
NullPointerException always occur in SparkDl4jMultiLayer

### ISSUE THREAD

**Issue by everpeace** [SkymindIO/deeplearning4j#159]
[This line](https://github.com/SkymindIO/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/impl/multilayer/SparkDl4jMultiLayer.java#L51) always cause a null pointer exception because `conf` is always null in this constructor.

Can the following resolve this issue??

```
public SparkDl4jMultiLayer(SparkContext sparkContext, MultiLayerNetwork network) {
    ....
    this.conf = network.getLayerWiseConfigurations().clone();
```

**Comment by agibsonccc** [comment]
Fixed in latest commit.
