### ISSUE TITLE
Deeplearning4j for time series prediction

### ISSUE THREAD

**Issue by CORolim** [SkymindIO/deeplearning4j#24]
An interesting feature of dl4j could be the support for time series prediction.

As stated by Adam
"The pieces are there, but I don't have the basic support in place for "automatic vectorization" of time series data, however there is an implementation of the viterbi algorithm in there.
The pieces would be very similar to the moving window text classification."

Regards

Carlos

**Comment by agibsonccc** [comment]
This is in master now. There are some simple utils for vectorizing time series (moving averages), other than that FFT and te other relevant DSP are in nd4j.
