### ISSUE TITLE
Recursive auto encoders

### ISSUE THREAD

**Issue by ErikTromp** [SkymindIO/deeplearning4j#43]
For modularity, it would be nice to have a recursive auto encoder class present in DL4J. The basic building blocks should be there and I think it will benefit users of the framework.

**Comment by agibsonccc** [comment]
I'll be getting this in to the 0.0.3.3 release.

**Comment by ErikTromp** [comment]
Oh wow, that'd be great. Really looking forward to this one!

**Comment by agibsonccc** [comment]
So I'm sitting on the unsupervised variant right now. What architecture were you targeting? SemiSupervised, or..?

**Comment by agibsonccc** [comment]
I'm going to close this: if you want semi supervised, open up a feature request for the next release.

**Comment by ErikTromp** [comment]
Wow, I guess you were too fast for me :) Semi-supervised would be my wish.
Either way, very nice progress, going to test around a bit.
